---
# tasks file for AnsibleRoleForLocalhostSetup
    - name: Upgrade the OS
      apt:
        name: "*"
        state: latest


    - name: Remove Unnecesary Software
      apt:
        pkg:
          - gnome-mahjongg
          - gnome-mines
          - gnome-sudoku
          - gnome-boxes
          - virt-manager
        state: absent

    - name: Install apt software
      apt:
        pkg:
          - git
          - nautilus
          - gnome-terminal
          - net-tools
          - curl
          - wget
          - snapd
          - python3
          - python3-pip
          - python3-tk
          - nano
          - vim
          - apache2

    - name: Install VirtualBox
      apt:
        deb: https://download.virtualbox.org/virtualbox/6.1.0/virtualbox-6.1_6.1.0-135406~Ubuntu~bionic_amd64.deb

    - name: Install Google Chrome
      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: Import Visual Studio Code apt key
      apt_key:
        url: 'https://packages.microsoft.com/keys/microsoft.asc'
        state: present
   
    - name: Enable Visual Studio Code repo
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        filename: vscode
        state: present

    - name: Install Visual Studio Code
      apt:
        name: code

    - name: Configure SSH Private Key
      copy:
        src: id_rsa
        dest: ~/.ssh
      become: false

    - name: Configure SSH Public Key
      copy:
        src: id_rsa.pub
        dest: ~/.ssh
      become: false

    - name: Download Vundle
      git:
        repo: "https://github.com/VundleVim/Vundle.vim.git"
        dest: ~/.vim/bundle/Vundle.vim
        clone: yes
      become: false

    - name: Configure Vundle
      copy:
        src: vimrc
        dest: ~/.vimrc
      become: false

    - name: Enable multiverse repository
      apt_repository:
        repo: "{{ item }}"
      loop:
        - "deb http://archive.ubuntu.com/ubuntu/ bionic multiverse"
        - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates multiverse"
        - "deb http://security.ubuntu.com/ubuntu/ bionic-security multiverse"

    - name: Enable Apache2
      service:
        name: apache2
        enabled: yes